name: sam_clean
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.5.7=hbcca054_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libblas=3.9.0=17_linux64_openblas
  - libcblas=3.9.0=17_linux64_openblas
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.1.0=he5830b7_0
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libgomp=13.1.0=he5830b7_0
  - liblapack=3.9.0=17_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.23=pthreads_h80387f5_0
  - libsqlite=3.42.0=h2797004_0
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=h166bdaf_4
  - ncurses=6.4=hcb278e6_0
  - openssl=3.1.1=hd590300_1
  - pandas=2.0.2=py310h7cbd5c2_0
  - pip=23.1.2=pyhd8ed1ab_0
  - python=3.10.8=h4a9ceb5_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.10=3_cp310
  - pytz=2023.3=pyhd8ed1ab_0
  - readline=8.2=h8228510_1
  - setuptools=67.7.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - tk=8.6.12=h27826a3_0
  - tzdata=2023c=h71feb2d_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
    - absl-py==1.4.0
    - anyio==3.7.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - astunparse==1.6.3
    - attrs==23.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - bleach==6.0.0
    - cachetools==5.3.1
    - certifi==2023.5.7
    - cffi==1.15.1
    - charset-normalizer==3.1.0
    - cmake==3.26.4
    - coloredlogs==15.0.1
    - comm==0.1.3
    - contourpy==1.1.0
    - cycler==0.11.0
    - debugpy==1.6.7
    - decorator==5.1.1
    - defusedxml==0.7.1
    - einops==0.6.1
    - exceptiongroup==1.1.1
    - executing==1.2.0
    - fastjsonschema==2.17.1
    - filelock==3.12.2
    - flatbuffers==23.5.26
    - fonttools==4.40.0
    - fqdn==1.5.1
    - gast==0.4.0
    - google-auth==2.20.0
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - grpcio==1.54.2
    - h5py==3.9.0
    - humanfriendly==10.0
    - idna==3.4
    - imageio==2.31.1
    - ipykernel==6.23.2
    - ipython==8.14.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.6
    - isoduration==20.11.0
    - jax==0.4.12
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonpointer==2.4
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-client==8.2.0
    - jupyter-console==6.6.3
    - jupyter-core==5.3.1
    - jupyter-events==0.6.3
    - jupyter-server==2.6.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.7
    - kaggle==1.5.13
    - keras==2.12.0
    - kiwisolver==1.4.4
    - lazy-loader==0.2
    - libclang==16.0.0
    - lit==16.0.6
    - markdown==3.4.3
    - markupsafe==2.1.3
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - mistune==3.0.1
    - ml-dtypes==0.2.0
    - monai==1.2.0
    - mpmath==1.3.0
    - nbclassic==1.0.0
    - nbclient==0.8.0
    - nbconvert==7.6.0
    - nbformat==5.9.0
    - nest-asyncio==1.5.6
    - networkx==3.1
    - nibabel==5.1.0
    - notebook==6.5.4
    - notebook-shim==0.2.3
    - numpy==1.23.5
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - oauthlib==3.2.2
    - onnx==1.14.0
    - onnxruntime==1.15.1
    - opencv-python==4.7.0.72
    - opt-einsum==3.3.0
    - overrides==7.3.1
    - packaging==23.1
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.5.0
    - platformdirs==3.7.0
    - prometheus-client==0.17.0
    - prompt-toolkit==3.0.38
    - protobuf==4.23.3
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pycocotools==2.0.6
    - pycparser==2.21
    - pygments==2.15.1
    - pyparsing==3.1.0
    - pyrsistent==0.19.3
    - python-json-logger==2.0.7
    - python-slugify==8.0.1
    - pytorch-ssim==0.1
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzmq==25.1.0
    - qtconsole==5.4.3
    - qtpy==2.3.1
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rsa==4.9
    - scikit-image==0.21.0
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - seaborn==0.12.2
    - segment-anything==1.0
    - send2trash==1.8.2
    - simpleitk==2.2.1
    - sniffio==1.3.0
    - soupsieve==2.4.1
    - split-folders==0.5.1
    - stack-data==0.6.2
    - sympy==1.12
    - tensorboard==2.12.3
    - tensorboard-data-server==0.7.1
    - tensorboardx==2.6.1
    - tensorflow==2.12.0
    - tensorflow-estimator==2.12.0
    - tensorflow-io-gcs-filesystem==0.32.0
    - termcolor==2.3.0
    - terminado==0.17.1
    - text-unidecode==1.3
    - threadpoolctl==3.1.0
    - tifffile==2023.4.12
    - tinycss2==1.2.1
    - torch==2.0.1
    - torchvision==0.15.2
    - tornado==6.3.2
    - tqdm==4.65.0
    - traitlets==5.9.0
    - triton==2.0.0
    - typing-extensions==4.6.3
    - uri-template==1.3.0
    - urllib3==1.26.16
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.0
    - werkzeug==2.3.6
    - widgetsnbextension==4.0.7
    - wrapt==1.14.1
prefix: /home/uriel/miniconda3/envs/uriel_sam_clean
